### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by qzqs** [AstroGypsophila/TryGankMaster#1]
我用了作者的切换主题的方法，但是怎么都改变不了Toolbar以外的主题颜色，怎么调整都是原来的颜色，作者切换主题是参考那些资料呢

**Comment by AstroGypsophila** [comment]
@qzqs 对于改变 TryGank 页面颜色，主要是改变 Status Bar (LOLLIPOP 以后)、Toolbar 以及页面 Activity theme。在切换主题颜色时候，记录当前所选，我还在基类 (AppSwipeBackActivity.java) 中写了改变 theme 设置，以便打开新页面时也能响应。
